### PR TITLE
Docs and release notes for gp nodes and other nodes.

### PR DESCRIPTION
**Pull request by 3DSinghVFX**
I have added the docs and release notes for grease pencil nodes, and other nodes that are added into Animation Nodes.

### CODE REVIEW

**Comment by OmarEmaraDev** [comment]
Many thanks Kuldeep!

By the way, if you want, you can also add an example for GP nodes in the Key Features in the index page. It is ok to duplicate contents in this case. You may also add one for the scatter node if you want.

**Comment by 3DSinghVFX** [comment]
> Many thanks Kuldeep!

You're always welcome :)

> By the way, if you want, you can also add an example for GP nodes in the Key Features in the index page. It is ok to duplicate contents in this case. You may also add one for the scatter node if you want.

Okay. I'll make examples for GP nodes, and also for Scatter node.

I have a small query, do I need to explain every step of the example or just brief information what is in the example?

**Comment by OmarEmaraDev** [comment]
> I have a small query, do I need to explain every step of the example or just brief information what is in the example?

If you need to explain the example in details then the example is probably more complicated that it should be. Simple examples with simple explanations should be provided. No need for detailed steps. Just like the other examples.

**Comment by 3DSinghVFX** [comment]
> > I have a small query, do I need to explain every step of the example or just brief information what is in the example?
> 
> If you need to explain the example in details then the example is probably more complicated that it should be. Simple examples with simple explanations should be provided. No need for detailed steps. Just like the other examples.

Okay, thanks.

**Pull request merged**
